# Generated by Django 5.0.7 on 2024-07-16 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="user",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="user",
        ),
    ]
